### PR TITLE
Added RAML basic example

### PR DESCRIPTION
**Pull request by PMSanelib**

### CODE REVIEW

**Comment by ghost** [comment]
@PMSanelib 
Can we have some basic details about this commit ?
What is the purpose of this ? How it is implemented or going to be implement in eBOSS ?
Basic doc is required to understand about RAML and it's functionality.
Thanks.

**Comment by PMSanelib** [comment]
I have committed basic description file but it is in rtf  format.

**Comment by sannimodi** [comment]
Accepting pull as sample doc.

We need all markdown and raml files for this scope. Do add for eBoss only.

**Comment by sannimodi** [comment]
Branch is kept open for documents.

**Pull request merged**
